"""Initial migration

Revision ID: 114dacbd1620
Revises:
Create Date: 2025-10-12 14:23:31.381736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = '114dacbd1620'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    dialect_name = bind.dialect.name if bind else None

    # ### commands auto generated by Alembic - please adjust! ###
    if dialect_name == "sqlite":
        with op.batch_alter_table('user', recreate='auto') as batch_op:
            batch_op.alter_column('full_name',
                       existing_type=sa.TEXT(),
                       type_=AutoString(),
                       existing_nullable=True)
            batch_op.alter_column('home_lat',
                       existing_type=sa.REAL(),
                       type_=sa.Float(),
                       existing_nullable=True)
            batch_op.alter_column('home_lng',
                       existing_type=sa.REAL(),
                       type_=sa.Float(),
                       existing_nullable=True)
            batch_op.alter_column('mylife_json',
                       existing_type=sa.TEXT(),
                       type_=sa.JSON(),
                       existing_nullable=False,
                       server_default=sa.text("'{}'"),
                       existing_server_default=sa.text("'{}'"))
    else:
        op.alter_column('user', 'full_name',
                   existing_type=sa.TEXT(),
                   type_=AutoString(),
                   existing_nullable=True)
        op.alter_column('user', 'home_lat',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('user', 'home_lng',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('user', 'mylife_json',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=False,
                   existing_server_default=sa.text("'{}'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    dialect_name = bind.dialect.name if bind else None

    # ### commands auto generated by Alembic - please adjust! ###
    if dialect_name == "sqlite":
        with op.batch_alter_table('user', recreate='auto') as batch_op:
            batch_op.alter_column('mylife_json',
                       existing_type=sa.JSON(),
                       type_=sa.TEXT(),
                       existing_nullable=False,
                       server_default=sa.text("'{}'"),
                       existing_server_default=sa.text("'{}'"))
            batch_op.alter_column('home_lng',
                       existing_type=sa.Float(),
                       type_=sa.REAL(),
                       existing_nullable=True)
            batch_op.alter_column('home_lat',
                       existing_type=sa.Float(),
                       type_=sa.REAL(),
                       existing_nullable=True)
            batch_op.alter_column('full_name',
                       existing_type=AutoString(),
                       type_=sa.TEXT(),
                       existing_nullable=True)
    else:
        op.alter_column('user', 'mylife_json',
                   existing_type=sa.JSON(),
                   type_=sa.TEXT(),
                   existing_nullable=False,
                   existing_server_default=sa.text("'{}'"))
        op.alter_column('user', 'home_lng',
                   existing_type=sa.Float(),
                   type_=sa.REAL(),
                   existing_nullable=True)
        op.alter_column('user', 'home_lat',
                   existing_type=sa.Float(),
                   type_=sa.REAL(),
                   existing_nullable=True)
        op.alter_column('user', 'full_name',
                   existing_type=AutoString(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    # ### end Alembic commands ###
