"""Add linked_job_id to JobApplication

Revision ID: 32acdb26c7c4
Revises: 0001_create_base
Create Date: 2025-10-13 13:19:25.211256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32acdb26c7c4'
down_revision: Union[str, None] = '0001_create_base'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping chatkit tables if they don't exist
    try:
        op.drop_index('ix_chatkit_thread_item_created_at', table_name='chatkit_thread_item')
        op.drop_index('ix_chatkit_thread_item_thread_id', table_name='chatkit_thread_item')
        op.drop_index('ix_chatkit_thread_item_type', table_name='chatkit_thread_item')
        op.drop_table('chatkit_thread_item')
        op.drop_table('chatkit_thread')
    except:
        pass

    op.add_column('jobapplication', sa.Column('linked_job_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobapplication_linked_job_id'), 'jobapplication', ['linked_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobapplication_linked_job_id'), table_name='jobapplication')
    op.drop_column('jobapplication', 'linked_job_id')
    op.create_table('chatkit_thread',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chatkit_thread_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chatkit_thread_item',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chatkit_thread.id'], name='chatkit_thread_item_thread_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chatkit_thread_item_pkey')
    )
    op.create_index('ix_chatkit_thread_item_type', 'chatkit_thread_item', ['type'], unique=False)
    op.create_index('ix_chatkit_thread_item_thread_id', 'chatkit_thread_item', ['thread_id'], unique=False)
    op.create_index('ix_chatkit_thread_item_created_at', 'chatkit_thread_item', ['created_at'], unique=False)
    # ### end Alembic commands ###
